### ISSUE TITLE
Step 99: There was an error, check the console for more details

### ISSUE THREAD

**Issue by enrique131** [aschmelyun/subvert#19]
Any idea why i see this? 
Is on a synology NAS and i am not sure where can i access a console here 
![step99](https://user-images.githubusercontent.com/45486873/230339855-d20a1366-28b6-4d1c-a73a-e713ddd8f095.png)
Thanks

**Comment by carlric** [comment]
I'm having the same issue.

**Comment by aschmelyun** [comment]
@enrique131 and @carlric 

I recently pushed out an update to the container image that should display the actual error on the frontend instead of this generic message. Pull the `aschmelyun/subvert:latest` image and use it, and let me know what the error returned is in a new issue.

Thanks, and hope this helps get to the bottom of it!

**Comment by enrique131** [comment]
I removed the docker, installed with the aschmelyun/subvert:latest as indicated but i am afraid i have the same error again.
