### ISSUE TITLE
Error when trying to subtitle video or audio

### ISSUE THREAD

**Issue by andytuinman3** [aschmelyun/subvert#22]
Whenever I upload a video or even audio alone from that video I get the following error:

Maximum content size limit (26214400) exceeded (26261586 bytes read)

My file is 300mb for the video file and also tried it with a 30mb audio file. Upload and max memory set to 2048MB. 

How can I fix this?

**Comment by aschmelyun** [comment]
This issue is due to hitting OpenAI's Whisper API upload limit. I'll need to implement batching to prevent this from happening, but that'll require refactoring large parts of the app to handle the different content generation regardless of how many batches there are.

Closing this issue, opened #24 to track this.
